PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
	  ?s a dblp:Publication ;
	     dblp:doi ?doi ;
	     dblp:title ?title ;
	     dblp:yearOfPublication ?year ;
	     dblp:authoredBy ?author .	
}
WHERE {
      ?s a dblp:Publication ;
      dblp:doi ?doi ;
      dblp:title ?title ;
      dblp:yearOfPublication ?year ;
      dblp:authoredBy ?author .
      FILTER ( ?year IN ( "2023"^^<http://www.w3.org/2001/XMLSchema#gYear>, "2022"^^<http://www.w3.org/2001/XMLSchema#gYear>, "2021"^^<http://www.w3.org/2001/XMLSchema#gYear> ) )
}